version: "3.9"

services:
  grafana:
    extends:
      file: docker-compose.yaml
      service: grafana
    ports:
      - "3000:3000"

  influxdb:
    extends:
      file: docker-compose.yaml
      service: influxdb
    ports:
      - "8086:8086"

volumes:
  grafana_data:
    driver: local
  influxdb_config:
    driver: local
  influxdb_data:
    driver: local

networks:
  node-network:
    driver: bridge