version: "3.9"

services:
  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      TZ: "Europe/Moscow"
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_USER: ${SMTP_USER}
      GF_SMTP_PASSWORD: ${SMTP_PASSWORD}
      GF_SMTP_SKIP_VERIFY: true
      GF_SMTP_FROM_ADDRESS: ${SMTP_USER}
      GF_SMTP_FROM_NAME: KGBB
    networks:
      - node-network

  influxdb:
    image: influxdb:2
    container_name: influx
    restart: unless-stopped
    ports:
      - "8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: influx_admin
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: influx_admin
      DOCKER_INFLUXDB_INIT_ORG: KGBB
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
    volumes:
      - influxdb_data:/etc/influxdb2
      - influxdb_config:/var/lib/influxdb2
    networks:
      - node-network

volumes:
  grafana_data:
    driver: local
  influxdb_config:
    driver: local
  influxdb_data:
    driver: local

networks:
  node-network:
    driver: bridge